vim.g.mapleader = ' '
vim.g.maplocalleader = ' '

vim.opt.laststatus = 2
vim.opt.number = true
vim.opt.cursorline = true
vim.opt.cursorcolumn = true
vim.opt.signcolumn = "yes"
vim.opt.mousescroll = "ver:8,hor:6"
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.wrap = false
vim.opt.clipboard = 'unnamedplus'
vim.opt.scrolloff = 10
vim.opt.sidescrolloff = 8
vim.opt.undofile = true
-- vim.opt.foldcolumn = '0'
vim.opt.foldlevelstart = 99
vim.opt.foldmethod = "expr"
vim.opt.foldexpr = "nvim_treesitter#foldexpr()"
vim.opt.hlsearch = true
vim.opt.swapfile = false
