live_config_reload = true

import = [
  "~/.config/alacritty/themes/tokyonight_day.toml"
]

[font]
size = 11.0

[font.glyph_offset]
y = -1

[font.offset]
y = -2

[keyboard]
bindings = [
  { key = "Insert", mods = "Shift", action = "Paste" },
  { key = "F5", mods = "Control", chars = "\u001B[>15;5~" },
]
