[general]
live_config_reload = true

import = [
  "~/.cache/wal/colors-alacritty.toml"
]

[font]
size = 11
glyph_offset = { y = -1 }
offset = { y = -2 }

[keyboard]
bindings = [
  { key = "Insert", mods = "Shift", action = "Paste" },
  { key = "F5", mods = "Control", chars = "\u001B[>15;5~" },
]
