set -g mouse on
set -g repeat-time 700
set -g default-terminal "tmux-256color"
set -a terminal-features 'xterm-256color:RGB'

set -g prefix C-Space

bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

bind - split-window -v -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"

bind c new-window -c "#{pane_current_path}"

