gui:
  scrollHeight: 8
  showFileTree: false
  nerdFontsVersion: "3"
git:
  branchLogCmd: 'git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium --stat {{branchName}} --'
  allBranchesLogCmd: 'git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium --stat'
os:
  editPreset: nvim
keybinding:
  universal:
    gotoTop: 'g'
    gotoBottom: 'G'
