#!/bin/sh
lock() {
    i3lock-fancy-rapid 5 3
}
RESULT=`echo -e "sleep\nlock\nlogout\nreboot\nshutdown" | fzf`
set -m
case "$RESULT" in
    "sleep")
        lock; sleep 0.5; systemctl suspend
        ;;
    "lock")
        lock
        ;;
    "logout")
        setxkbmap -option; who | cut -d' ' -f1 | xargs pkill -Kill -u
        ;;
    "reboot")
        shutdown -r now
        ;;
    "shutdown")
        shutdown now
        ;;
esac
