#!/bin/sh
lock() {
    find ~/images/wallpaper | sort -R | tail -1 | xargs -I {} i3lock -i "{}" -et
}
RESULT=`echo -e "sleep\nlock\nlogout\nreboot\nshutdown" | dmenu "$@"`
case "$RESULT" in
    "sleep")
        lock; sleep 0.5; systemctl suspend
        ;;
    "lock")
        lock
        ;;
    "logout")
        setxkbmap -option
        who | cut -d' ' -f1 | xargs pkill -Kill -u
        ;;
    "reboot")
        shutdown -r now
        ;;
    "shutdown")
        shutdown now
        ;;
esac
